"""remove unique user name contraint

Revision ID: c82208ade892
Revises: 5e72a7e5fa0d
Create Date: 2021-04-07 20:19:51.107973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82208ade892'
down_revision = '5e72a7e5fa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('RepoStrings_user_name_key', 'RepoStrings', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('RepoStrings_user_name_key', 'RepoStrings', ['user_name'])
    # ### end Alembic commands ###
